### ISSUE TITLE
Panfork issue

### ISSUE THREAD

**Issue by katyo** [fb87/nixos-orangepi-5x#1]
Have you test panfork?
Seems hardware acceleration still not working right now.

Where is a diff of dmesg with ubuntu:
```diff
 vdd_gpu_s0: supplied by vcc5v0_sys
+rockchip-pm-domain fd8d8000.power-management:power-controller: Looking up gpu-supply from device tree
+rockchip-pm-domain fd8d8000.power-management:power-controller: Looking up gpu-supply property in node /power-management@fd8d8000/power-controller failed
-rockchip-pm-domain fd8d8000.power-management:power-controller: Looking up gpu-supply from device tree
-rockchip-pm-domain fd8d8000.power-management:power-controller: Looking up gpu-supply property in node /power-management@fd8d8000/power-controller failed
 mali fb000000.gpu: Kernel DDK version g17p0-01eac0
 mali fb000000.gpu: Looking up mali-supply from device tree
 mali fb000000.gpu: Looking up mem-supply from device tree
 mali fb000000.gpu: Looking up mali-supply from device tree
 vdd_gpu_s0: could not add device link fb000000.gpu: -EEXIST
 vdd_gpu_s0: Failed to create debugfs directory
 mali fb000000.gpu: Looking up mem-supply from device tree
 vdd_gpu_s0: could not add device link fb000000.gpu: -EEXIST
 vdd_gpu_s0: Failed to create debugfs directory
 mali fb000000.gpu: Looking up mali-supply from device tree
 vdd_gpu_s0: could not add device link fb000000.gpu: -EEXIST
 vdd_gpu_s0: Failed to create debugfs directory
 mali fb000000.gpu: bin=0
 mali fb000000.gpu: leakage=20
 mali fb000000.gpu: Looking up mali-supply from device tree
 debugfs: Directory 'fb000000.gpu-mali' with parent 'vdd_gpu_s0' already present!
+mali fb000000.gpu: pvtm=883
+mali fb000000.gpu: pvtm-volt-sel=3
+mali fb000000.gpu: avs=0
-mali fb000000.gpu: pvtm=883
-mali fb000000.gpu: pvtm-volt-sel=3
-mali fb000000.gpu: avs=0
 W : [File] : drivers/gpu/arm/bifrost/platform/rk/mali_kbase_config_rk.c; [Line] : 143; [Func] : kbase_platform_rk_init(); power-off-delay-ms not available.
 mali fb000000.gpu: GPU hardware issue table may need updating:
 mali fb000000.gpu: GPU identified as 0x7 arch 10.8.6 r0p0 status 0
 mali fb000000.gpu: No priority control manager is configured
 mali fb000000.gpu: No memory group manager is configured
 mali fb000000.gpu: Protected memory allocator not available
-mali fb000000.gpu: Capping CSF_FIRMWARE_TIMEOUT to CSF_FIRMWARE_PING_TIMEOUT
-mali fb000000.gpu: Couldn't find power_model DT node matching 'arm,mali-simple-power-model'
-mali fb000000.gpu: Error -22, no DT entry: mali-simple-power-model.static-coefficient = 1*
+mali fb000000.gpu: Capping CSF_FIRMWARE_TIMEOUT to CSF_FIRMWARE_PING_TIMEOUT
+mali fb000000.gpu: Couldn't find power_model DT node matching 'arm,mali-simple-power-model'
+mali fb000000.gpu: Error -22, no DT entry: mali-simple-power-model.static-coefficient = 1*
 mali fb000000.gpu: Error -22, no DT entry: mali-simple-power-model.dynamic-coefficient = 1*
 mali fb000000.gpu: Error -22, no DT entry: mali-simple-power-model.ts = 4*
 mali fb000000.gpu: Error -22, no DT entry: mali-simple-power-model.thermal-zone = ''
 mali fb000000.gpu: Using configured power model mali-lodx-power-model, and fallback mali-simple-power-model
 mali fb000000.gpu: l=10000 h=85000 hyst=5000 l_limit=0 h_limit=800000000 h_table=0
 mali fb000000.gpu: Probed as mali0
-I : [File] : drivers/gpu/arm/mali400/mali/linux/mali_kernel_linux.c; [Line] : 406; [Func] : mali_module_init(); svn_rev_string_from_arm of this mali_ko is '', rk_ko_ver is '5', built at '12:52:31', on 'Jul 25 2023'.
+I : [File] : drivers/gpu/arm/mali400/mali/linux/mali_kernel_linux.c; [Line] : 406; [Func] : mali_module_init(); svn_rev_string_from_arm of this mali_ko is '', rk_ko_ver is '5', built at '00:00:00', on 'Jan  1 1980'.
-mali fb000000.gpu: Loading Mali firmware 0x1010000
-mali fb000000.gpu: Mali firmware git_sha: a9b9d413d30169284dfbc5c68e8c65fdaeca28b7
```

Seemingly firmware hasn't loads at all.

**Comment by fb87** [comment]
GPU tends to work with Wayland, I am using X11 hence not yet checked.

**Comment by katyo** [comment]
@fb87 It doesn't work with wayland and x11 for me.

**Comment by fb87** [comment]
@katyo thanks, let me see if I can do something. Ubuntu adding some userspace libraries in order to make Wayland/X11 to work with mali.

**Comment by fb87** [comment]
@katyo Mali should now work on Wayland, check https://github.com/fb87/nixos-orangepi-5x/releases/tag/v2023.10-05.kernel-v5.10.x.
Note: I'm not yet able to force gnome/gdm to use Wayland, have to stick with `sway` as of now.

**Comment by katyo** [comment]
@fb87 I already enabled those config options but it still not working for me (Gnome).
```
CONFIG_FW_LOADER_COMPRESS=y
CONFIG_FW_LOADER_COMPRESS_XZ=y
```

**Comment by fb87** [comment]
Gnome/Gdm is kinda pain, I have not able to force them all to use Wayland also. `ps afx | grep X11` to see if Gnome uses X11 or not, currently, I am see `sway` working (`weston` also work).

**Comment by katyo** [comment]
@fb87 Could you show your dmesg log?

**Comment by phaitonican** [comment]
Doesn't work for me to. I start SuperTuxKart with --render-driver=vulkan it says vulkan is unavailable also ps2 emulator is very laggy on vulkan

**Comment by katyo** [comment]
I don't sure that vulkan will works soon on pancsf compatible hardware.

**Comment by phaitonican** [comment]
Yes but why supertuxkart is super laggy with OpenGl??

**Comment by fb87** [comment]
Boot log @katyo [dmesg.log](https://github.com/fb87/nixos-orangepi-5x/files/13035121/dmesg.log)

**Comment by fb87** [comment]
> Yes but why supertuxkart is super laggy with OpenGl??

Mali userspace driver tend to support OpenGLES not OpenGL hence it might not work AFAIK. I'm looking for on this OpenGL support not no luck till now :(.

**Comment by katyo** [comment]
@fb87 Thanks!
